drop table if exists url;

create table urls
(
    id         bigint generated by default as identity not null,
    name       varchar(255),
    created_at timestamp                               not null,
    constraint pk_url primary key (id)
);

drop table if exists url_check;

create table url_checks
(
    id          bigint generated by default as identity not null,
    status_code integer                                 not null,
    title       varchar(255),
    h1          varchar(255),
    description clob,
    url_id      bigint,
    created_at  timestamp                               not null,
    constraint pk_url_check primary key (id)
);

create index ix_url_check_url_id on url_checks (url_id);
alter table url_checks
    add constraint fk_url_check_url_id foreign key (url_id) references urls (id) on delete restrict on update restrict;